### ISSUE TITLE
Browser history needs a DOM

### ISSUE THREAD

**Issue by denny64** [salvoravida/redux-first-history#1]
I've set it up as suggested in the README file, but getting the error "Browser history needs a DOM".

Using react router v4 + react loadable + SSR.

Any ideas?

Thanks

**Comment by salvoravida** [comment]
@denny64 feel free to re-open as soon as you can share more code/detail.

**Comment by iiroj** [comment]
If you followed the example in the [README.md](https://github.com/salvoravida/redux-first-history/blob/master/README.md), you'll have used the `createBrowserHistory` method of the `history` package. This does not work server-side.

Here's my version where you can supply the current location pathname to a `configureStore` method which works server-side and returns the `store` and `history` (don't really need the history object server-side, since you already have the pathname):

```ts
import { createBrowserHistory, createMemoryHistory } from 'history'
import { composeWithDevTools } from 'redux-devtools-extension'
import { createReduxHistoryContext } from 'redux-first-history'
import {
  Middleware,
  createStore,
  combineReducers,
  applyMiddleware
} from 'redux'

const composeMiddleware = (...middleware: Middleware[]) =>
  process.env.NODE_ENV === 'production'
    ? applyMiddleware(...middleware)
    : composeWithDevTools(applyMiddleware(...middleware))

const createHistory = (pathname?: string) =>
  createReduxHistoryContext({
    history:
      typeof window === 'undefined' && pathname
        ? createMemoryHistory({ initialEntries: [pathname] })
        : createBrowserHistory()
  })

type ConfigureStore = {
  pathname?: string
}

export default function configureStore({ pathname }: ConfigureStore = {}) {
  const { createReduxHistory, routerMiddleware, routerReducer } = createHistory(
    pathname
  )

  const store = createStore(
    combineReducers({ router: routerReducer }),
    composeMiddleware(routerMiddleware)
  )

  const history = createReduxHistory(store)

  return { history, store }
}
```

**Comment by salvoravida** [comment]
@iiroj thanks! i have pinned this SSR support example
